//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 A 的本地化字符串。
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B 的本地化字符串。
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BlueColor 的本地化字符串。
        /// </summary>
        internal static string BlueColor {
            get {
                return ResourceManager.GetString("BlueColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C 的本地化字符串。
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D 的本地化字符串。
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DatabaseConnectionString 的本地化字符串。
        /// </summary>
        internal static string DatabaseConnectionString {
            get {
                return ResourceManager.GetString("DatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FinalView_Message1 的本地化字符串。
        /// </summary>
        internal static string FinalView_Message1 {
            get {
                return ResourceManager.GetString("FinalView_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FinalView_Message2 的本地化字符串。
        /// </summary>
        internal static string FinalView_Message2 {
            get {
                return ResourceManager.GetString("FinalView_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FinalView_Message3 的本地化字符串。
        /// </summary>
        internal static string FinalView_Message3 {
            get {
                return ResourceManager.GetString("FinalView_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GreenColor 的本地化字符串。
        /// </summary>
        internal static string GreenColor {
            get {
                return ResourceManager.GetString("GreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message6 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message6 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message6_1 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message6_1 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message7 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message7 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message7_1 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message7_1 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message8 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message8 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message8_1 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message8_1 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message9 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message9 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message9_1 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message9_1 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LanguageInformation 的本地化字符串。
        /// </summary>
        internal static string LanguageInformation {
            get {
                return ResourceManager.GetString("LanguageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LanguagePath 的本地化字符串。
        /// </summary>
        internal static string LanguagePath {
            get {
                return ResourceManager.GetString("LanguagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Languages 的本地化字符串。
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyyMMdd 的本地化字符串。
        /// </summary>
        internal static string LisFileNameFormat {
            get {
                return ResourceManager.GetString("LisFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LisFilesPath 的本地化字符串。
        /// </summary>
        internal static string LisFilesPath {
            get {
                return ResourceManager.GetString("LisFilesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strAge 的本地化字符串。
        /// </summary>
        internal static string LisInfo_Age {
            get {
                return ResourceManager.GetString("LisInfo_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strBarcode 的本地化字符串。
        /// </summary>
        internal static string LisInfo_Barcode {
            get {
                return ResourceManager.GetString("LisInfo_Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strBirthday 的本地化字符串。
        /// </summary>
        internal static string LisInfo_Birthday {
            get {
                return ResourceManager.GetString("LisInfo_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strDateTime 的本地化字符串。
        /// </summary>
        internal static string LisInfo_DateTime {
            get {
                return ResourceManager.GetString("LisInfo_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strItem 的本地化字符串。
        /// </summary>
        internal static string LisInfo_Item {
            get {
                return ResourceManager.GetString("LisInfo_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strName 的本地化字符串。
        /// </summary>
        internal static string LisInfo_Name {
            get {
                return ResourceManager.GetString("LisInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strSampleID 的本地化字符串。
        /// </summary>
        internal static string LisInfo_SampleID {
            get {
                return ResourceManager.GetString("LisInfo_SampleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strSampleType 的本地化字符串。
        /// </summary>
        internal static string LisInfo_SampleType {
            get {
                return ResourceManager.GetString("LisInfo_SampleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strSex 的本地化字符串。
        /// </summary>
        internal static string LisInfo_Sex {
            get {
                return ResourceManager.GetString("LisInfo_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男 的本地化字符串。
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rds123 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_CheckInstrumentErrorMessage 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_CheckInstrumentErrorMessage {
            get {
                return ResourceManager.GetString("PopupWindow_CheckInstrumentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Message1 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Message1 {
            get {
                return ResourceManager.GetString("PopupWindow_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Message2 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Message2 {
            get {
                return ResourceManager.GetString("PopupWindow_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_TaskFinishedMessage 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_TaskFinishedMessage {
            get {
                return ResourceManager.GetString("PopupWindow_TaskFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Title_Administrators 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Title_Administrators {
            get {
                return ResourceManager.GetString("PopupWindow_Title_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Title_Information 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Title_Information {
            get {
                return ResourceManager.GetString("PopupWindow_Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Title_MessageBox 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Title_MessageBox {
            get {
                return ResourceManager.GetString("PopupWindow_Title_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Title_Wait 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Title_Wait {
            get {
                return ResourceManager.GetString("PopupWindow_Title_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrecheckView_CheckInstrument 的本地化字符串。
        /// </summary>
        internal static string PrecheckView_CheckInstrument {
            get {
                return ResourceManager.GetString("PrecheckView_CheckInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReagentInformation 的本地化字符串。
        /// </summary>
        internal static string ReagentInformation {
            get {
                return ResourceManager.GetString("ReagentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reagents 的本地化字符串。
        /// </summary>
        internal static string Reagents {
            get {
                return ResourceManager.GetString("Reagents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReagentSeries 的本地化字符串。
        /// </summary>
        internal static string ReagentSeries {
            get {
                return ResourceManager.GetString("ReagentSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HH:mm:ss 的本地化字符串。
        /// </summary>
        internal static string RemainingTimeFormat {
            get {
                return ResourceManager.GetString("RemainingTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectedReanents 的本地化字符串。
        /// </summary>
        internal static string SelectedReanents {
            get {
                return ResourceManager.GetString("SelectedReanents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 的本地化字符串。
        /// </summary>
        internal static string Separator1 {
            get {
                return ResourceManager.GetString("Separator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 = 的本地化字符串。
        /// </summary>
        internal static string Separator2 {
            get {
                return ResourceManager.GetString("Separator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 : 的本地化字符串。
        /// </summary>
        internal static string Separator3 {
            get {
                return ResourceManager.GetString("Separator3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , 的本地化字符串。
        /// </summary>
        internal static string Separator4 {
            get {
                return ResourceManager.GetString("Separator4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /RDS;component/Views/MainWindow.xaml 的本地化字符串。
        /// </summary>
        internal static string StartupUri {
            get {
                return ResourceManager.GetString("StartupUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}{1} 的本地化字符串。
        /// </summary>
        internal static string StringFormat2 {
            get {
                return ResourceManager.GetString("StringFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}{1}{2} 的本地化字符串。
        /// </summary>
        internal static string StringFormat3 {
            get {
                return ResourceManager.GetString("StringFormat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TaskFinish 的本地化字符串。
        /// </summary>
        internal static string TaskFinish {
            get {
                return ResourceManager.GetString("TaskFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 00:00:00 的本地化字符串。
        /// </summary>
        internal static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TwinkleAnimation 的本地化字符串。
        /// </summary>
        internal static string TwinkleAnimation {
            get {
                return ResourceManager.GetString("TwinkleAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WathetColor 的本地化字符串。
        /// </summary>
        internal static string WathetColor {
            get {
                return ResourceManager.GetString("WathetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
